import { Link } from 'react-router-dom';
import CdnImage from '../components/CdnImage';
import { SiteFooter } from '../components/SitePageParts';
import { useSEO } from '../utils/seo';
import './SitePages.css';
export default function AboutPage(){
  useSEO('关于本站','DeepPhilosophy：哲学著作、哲人资料与思想谱系。了解项目与内容整理原则。');
  return <article className="site-pages"><div className="s-shell"><section className="s-about-hero"><div><p className="s-kicker">About DeepPhilosophy</p><h1>让哲学，<br/>回到阅读之中。</h1><p>一本书，一位思想家，一条思想的来路。<br/>从具体的文本开始，慢慢建立自己的理解。</p><Link className="s-textlink" to="/genealogy">开始探索 ↗</Link></div><div className="s-about-image"><CdnImage src="/schools/现象学.webp" imageWidth={720} alt="现象学环境绘画" loading="eager"/><span>DeepPhilosophy · 思想与阅读</span></div></section><section className="s-about-essay"><div><p className="s-kicker">Why this place</p><h2>为什么做这个网站</h2></div><div><p>DeepPhilosophy 是一个由哲学爱好者整理的阅读网站。这里收录哲学著作、哲人资料与思想谱系，希望让原文和理解原文所需要的背景更容易找到。</p><p>你可以从一本书开始，也可以从一个困扰自己的问题开始。读到陌生的名字，就去认识那位思想家；遇到一个概念，再回到它所在的作品与讨论中。</p><p>本站会持续修订资料。哲学思想往往比一段简介更复杂，我们也希望保留这些分歧，让读者有机会继续往下读。</p></div></section><section className="s-principles" aria-label="内容整理原则"><div><small>01</small><h3>回到作品</h3><p>简介帮助进入原文。重要概念、论点和引文，尽量提供可追索的作品与出处。</p></div><div><small>02</small><h3>保留分歧</h3><p>区分作者、时代、传统与主题。呈现观点的关联，也说明它们之间的差异。</p></div><div><small>03</small><h3>持续修订</h3><p>承认资料仍有空缺。对译名、归属、目录与内容中的错误，逐项核对和修正。</p></div></section><section className="s-colophon"><div><p className="s-kicker">Made & maintained by</p><h2>@txdsyl_</h2><p>整理、设计与维护 DeepPhilosophy。<br/>感谢愿意阅读、反馈和帮助纠错的人。</p><a className="s-textlink" href="https://github.com/wqx-txdsyl/DeepPhilosophy" target="_blank" rel="noopener noreferrer">查看项目 ↗</a><br/><a className="s-textlink" href="https://github.com/wqx-txdsyl/DeepPhilosophy/issues" target="_blank" rel="noopener noreferrer">提交纠错与建议 ↗</a></div><div><p className="s-kicker">A few practical questions</p><h2>你可能想知道</h2><details className="s-faq"><summary>是否需要注册？</summary><p>浏览哲人、谱系和可读著作无需注册。登录主要用于同步阅读记录与批注。</p></details><details className="s-faq"><summary>为什么部分作品只有书目？</summary><p>书目收录与正文开放是两个状态。仅有书目资料的作品会明确标注，避免让读者误以为可以直接阅读。</p></details><details className="s-faq"><summary>发现内容或版权问题怎么办？</summary><p>请在项目反馈中提供页面链接、具体位置和可以核对的材料。涉及版权的反馈，请说明相关作品及权利信息，便于核查处理。</p></details></div></section></div><SiteFooter/></article>;
}
