//实证主义
const POSITIVISM_DATA={name:"实证主义",quote:"拒斥形而上学，只问如何不问为何。",quoteAuthor:"孔德",subtitle:"以自然科学为一切知识的典范",overview:"实证主义是19世纪由孔德创立的一场哲学和科学运动。",thinkers:[{name:"孔德",sub:"实证主义",era:"1798-1857",influence:10,key:"三阶段法则",works:["实证哲学教程"]},{name:"马赫",sub:"经验批判主义",era:"1838-1916",influence:9,key:"思维经济原则",works:["感觉的分析"]},{name:"涂尔干",sub:"社会学实证主义",era:"1858-1917",influence:9,key:"社会事实",works:["社会学方法的规则","自杀论"]},{name:"卡尔纳普",sub:"逻辑实证主义",era:"1891-1970",influence:9,key:"证实原则",works:["世界的逻辑构造"]}],relations:[{from:"孔德",to:"涂尔干",type:"影响"},{from:"马赫",to:"卡尔纳普",type:"影响"}],timeline:[],conclusion:"实证主义将科学方法推广到一切知识领域。",works:[],quotes:[],closingQuote:"拒斥形而上学。 — 孔德"};
const POSITIVISM_CIHAI=[{word:"三阶段法则",def:"人类知识从神学阶段到形而上学阶段到实证阶段的必然进步。",source:"孔德"},{word:"证实原则",def:"一个句子的意义就是它的证实方法，不能证实的命题无认知意义。",source:"卡尔纳普"},{word:"社会事实",def:"外在于个人意识、对个人有强制力的集体现象，必须当作物来研究。",source:"涂尔干"},{word:"思维经济原则",def:"科学理论不是揭示实在，而是经济地概述感觉经验。",source:"马赫"},{word:"科学层级",def:"数学-天文学-物理学-化学-生物学-社会学，从简单到复杂的科学排列。",source:"孔德"}];
const POSITIVISM_SUB_SCHOOLS=[{name:"孔德实证主义",era:"1830s-1857",desc:"三阶段法则，科学层级，社会学为科学皇后。"},{name:"经验批判主义",era:"1880s-1916",desc:"马赫将实证主义推向更彻底的现象主义。"},{name:"逻辑实证主义",era:"1920s-1930s",desc:"维也纳学派以证实原则拒绝形而上学。"}];
//社会学
const SOCIOLOGY_DATA={name:"社会学",quote:"把社会事实当作物来研究。",quoteAuthor:"涂尔干",subtitle:"以科学方法追问社会何以可能",overview:"社会学是19世纪从哲学中独立出来的新科学。",thinkers:[{name:"涂尔干",sub:"社会学",era:"1858-1917",influence:10,key:"社会事实",works:["自杀论","社会学方法的规则"]},{name:"韦伯",sub:"理解社会学",era:"1864-1920",influence:10,key:"铁笼",works:["新教伦理与资本主义精神"]},{name:"齐美尔",sub:"形式社会学",era:"1858-1918",influence:9,key:"形式与互动",works:["货币哲学"]},{name:"米尔斯",sub:"批判社会学",era:"1916-1962",influence:7,key:"社会学的想象力",works:["社会学的想象力"]}],relations:[{from:"涂尔干",to:"韦伯",type:"对立"},{from:"齐美尔",to:"韦伯",type:"影响"}],timeline:[],conclusion:"社会学是现代性的自我意识。",works:[],quotes:[],closingQuote:"把社会事实当作物来研究。 — 涂尔干"};
const SOCIOLOGY_CIHAI=[{word:"社会事实",def:"外在于个人、对个人有强制力的集体行为方式，必须当作物来研究。",source:"涂尔干"},{word:"失范",def:"社会规范崩溃或缺失的状态，个人不再知道什么是对的。",source:"涂尔干"},{word:"铁笼",def:"韦伯对现代理性官僚制的诊断，效率的代价是意义的丧失。",source:"韦伯"},{word:"理想型",def:"研究者从复杂现实中抽象出的纯粹概念工具。",source:"韦伯"},{word:"社会学的想象力",def:"在个人困扰与公共议题之间转换视角的能力。",source:"米尔斯"}];
const SOCIOLOGY_SUB_SCHOOLS=[{name:"涂尔干实证主义社会学",era:"1890s-1917",desc:"社会事实，自杀论，失范，机械/有机团结。"},{name:"韦伯理解社会学",era:"1900s-1920",desc:"理想型，新教伦理，铁笼，价值中立。"},{name:"形式社会学",era:"1900s-1918",desc:"齐美尔，社会交往的形式，货币哲学。"}];
//实用主义
const PRAGMATISM_DATA={name:"实用主义",quote:"真理即有用，意义在于效果。",quoteAuthor:"詹姆斯",subtitle:"以行动后果检验观念的真值",overview:"实用主义是19世纪末在美国诞生的第一个具有世界影响力的哲学运动。",thinkers:[{name:"皮尔士",sub:"实用主义",era:"1839-1914",influence:10,key:"实用主义准则",works:["如何使我们的观念清晰"]},{name:"威廉·詹姆斯",sub:"实用主义",era:"1842-1910",influence:10,key:"真理即有用",works:["实用主义","宗教经验种种"]},{name:"约翰·杜威",sub:"工具主义",era:"1859-1952",influence:9,key:"民主与教育",works:["民主与教育"]},{name:"罗蒂",sub:"新实用主义",era:"1931-2007",influence:8,key:"偶然反讽团结",works:["哲学与自然之镜"]}],relations:[{from:"皮尔士",to:"詹姆斯",type:"影响"},{from:"詹姆斯",to:"杜威",type:"影响"},{from:"杜威",to:"罗蒂",type:"影响"}],timeline:[],conclusion:"实用主义是美国对哲学史最原创的贡献。",works:[],quotes:[],closingQuote:"真理即有用。 — 威廉·詹姆斯"};
const PRAGMATISM_CIHAI=[{word:"实用主义准则",def:"一个概念的全部意义在于它的可想象的实践后果。",source:"皮尔士"},{word:"真理即有用",def:"真的信念是在经验中运作的、有用的。",source:"詹姆斯"},{word:"工具主义",def:"概念和理论是解决问题的工具，不是不变的真理。",source:"杜威"},{word:"新实用主义",def:"真理不是符合实在，是对话中同意的产物。",source:"罗蒂"},{word:"在做中学",def:"教育不是灌输，是培养经验，学习通过实践。",source:"杜威"}];
const PRAGMATISM_SUB_SCHOOLS=[{name:"皮尔士实用主义",era:"1870s-1914",desc:"实用主义准则，符号学，探究的逻辑。"},{name:"詹姆斯人本实用主义",era:"1890s-1910",desc:"实用主义方法，真理即有用，宗教经验研究。"},{name:"杜威工具主义",era:"1900s-1952",desc:"概念是工具，在做中学，民主是共同生活实验。"}];
