//过程哲学
const PROCESS_PHILOSOPHY_DATA={name:"过程哲学",quote:"实在是生成而非存在。",quoteAuthor:"怀特海",subtitle:"宇宙在创造性进展中不断向新质跃迁",overview:"过程哲学是20世纪由怀特海发展的形而上学体系。",thinkers:[{name:"怀特海",sub:"过程哲学",era:"1861-1947",influence:10,key:"实际事态",works:["过程与实在","科学与现代世界"]},{name:"哈茨霍恩",sub:"过程神学",era:"1897-2000",influence:8,key:"过程神学",works:["神圣的相对性"]},{name:"柏格森",sub:"生命哲学",era:"1859-1941",influence:9,key:"绵延",works:["创造进化论"]}],relations:[{from:"柏格森",to:"怀特海",type:"影响"},{from:"怀特海",to:"哈茨霍恩",type:"师生"}],timeline:[],conclusion:"怀特海的过程哲学是20世纪最雄心勃勃的形而上学。",works:[],quotes:[],closingQuote:"实在是生成而非存在。 — 怀特海"};
const PROCESS_PHILOSOPHY_CIHAI=[{word:"实际事态",def:"怀特海形而上学的最终单元，不是实体而是发生的事。",source:"怀特海"},{word:"摄入",def:"实际事态感受其他实际事态并将之纳入自己的综合。",source:"怀特海"},{word:"创造性进展",def:"宇宙不是存在而是生成，每一瞬间都有新颖出现。",source:"怀特海"},{word:"永恒客体",def:"纯潜能，可以被摄入为实际事态的性质或形式。",source:"怀特海"},{word:"两极上帝",def:"上帝有原初极和后果极，与宇宙一起生成。",source:"哈茨霍恩"}];
const PROCESS_PHILOSOPHY_SUB_SCHOOLS=[{name:"怀特海有机哲学",era:"1920s-1947",desc:"实际事态，摄入，创造性进展。"},{name:"过程神学",era:"1940s-present",desc:"哈茨霍恩以上帝与宇宙一起生成。"}];
//哲学人类学
const PHILOSOPHICAL_ANTHROPOLOGY_DATA={name:"哲学人类学",quote:"人是什么？",quoteAuthor:"康德",subtitle:"以哲学整合各学科对人的认识",overview:"哲学人类学是20世纪德国哲学的重要分支，追问人的特殊地位。",thinkers:[{name:"舍勒",sub:"哲学人类学",era:"1874-1928",influence:10,key:"人在宇宙中的位置",works:["人在宇宙中的位置"]},{name:"盖伦",sub:"哲学人类学",era:"1904-1976",influence:8,key:"未特化性",works:["人:他的本性和在世界中的位置"]},{name:"普莱斯纳",sub:"哲学人类学",era:"1892-1985",influence:8,key:"离心的位置",works:["有机体的阶段与人"]},{name:"卡西尔",sub:"符号哲学",era:"1874-1945",influence:9,key:"人是符号的动物",works:["人论"]}],relations:[{from:"舍勒",to:"盖伦",type:"影响"},{from:"舍勒",to:"普莱斯纳",type:"影响"}],timeline:[],conclusion:"人的未完成正是他的自由。",works:[],quotes:[],closingQuote:"人是什么？ — 康德"};
const PHILOSOPHICAL_ANTHROPOLOGY_CIHAI=[{word:"未特化性",def:"人的形态学特征是所有动物中最未完成的，逼迫人创造文化。",source:"盖伦"},{word:"离心的位置",def:"人永远不能完全在自己中，永远在自己之外。",source:"普莱斯纳"},{word:"精神",def:"舍勒认为人是能说不的能力的存在，精神超越生命。",source:"舍勒"},{word:"符号形式",def:"人通过符号接触世界，人是活在意义中的动物。",source:"卡西尔"},{word:"哲学人类学",def:"追问人作为整体是什么，整合生物学、心理学与社会学。",source:"舍勒"}];
const PHILOSOPHICAL_ANTHROPOLOGY_SUB_SCHOOLS=[{name:"舍勒形而上学人类学",era:"1920s-1928",desc:"精神，生命，冲动，人在宇宙中的特殊位置。"},{name:"盖伦制度人类学",era:"1940s-1976",desc:"人的生物缺陷逼迫人创造文化作为替代本能。"},{name:"卡西尔符号人类学",era:"1940s-1945",desc:"人是符号的动物，神话语言科学是人的符号形式。"}];
//科学哲学
const PHILOSOPHY_OF_SCIENCE_DATA={name:"科学哲学",quote:"科学何以成为科学？",quoteAuthor:"波普尔",subtitle:"追问科学的本质、方法与界限",overview:"科学哲学是20世纪分析哲学传统中追问科学是什么的哲学分支。",thinkers:[{name:"波普尔",sub:"批判理性主义",era:"1902-1994",influence:10,key:"可否证性",works:["科学发现的逻辑"]},{name:"库恩",sub:"历史主义",era:"1922-1996",influence:10,key:"范式革命",works:["科学革命的结构"]},{name:"费耶阿本德",sub:"方法论无政府主义",era:"1924-1994",influence:8,key:"怎么都行",works:["反对方法"]},{name:"拉卡托斯",sub:"研究纲领",era:"1922-1974",influence:8,key:"研究纲领",works:["科学研究纲领方法论"]}],relations:[{from:"波普尔",to:"库恩",type:"批判"},{from:"库恩",to:"费耶阿本德",type:"友谊"},{from:"波普尔",to:"拉卡托斯",type:"师生"}],timeline:[],conclusion:"科学哲学揭示科学不仅是积累事实。",works:[],quotes:[],closingQuote:"科学何以成为科学？ — 波普尔"};
const PHILOSOPHY_OF_SCIENCE_CIHAI=[{word:"可否证性",def:"科学分界的标准，理论必须敢于被否定才是科学的。",source:"波普尔"},{word:"范式",def:"公认的科学成就，为一科学共同体提供范例性问题和解法。",source:"库恩"},{word:"不可通约性",def:"新旧范式之间没有中立的标准来比较。",source:"库恩"},{word:"研究纲领",def:"由硬核和保护带构成，进步的研究纲领不断预测新颖事实。",source:"拉卡托斯"},{word:"怎么都行",def:"科学在历史上从未有任何唯一的方法。",source:"费耶阿本德"}];
const PHILOSOPHY_OF_SCIENCE_SUB_SCHOOLS=[{name:"批判理性主义",era:"1930s-1990s",desc:"波普尔，可否认性，猜想与反驳。"},{name:"历史主义",era:"1960s-1990s",desc:"库恩，范式，常规科学，科学革命。"},{name:"方法论无政府主义",era:"1970s-1990s",desc:"费耶阿本德，怎么都行。"}];
//西方马克思主义
const WESTERN_MARXISM_DATA={name:"西方马克思主义",quote:"回到黑格尔的马克思。",quoteAuthor:"卢卡奇",subtitle:"以文化批判和意识形态理论补充经济分析",overview:"西方马克思主义从卢卡奇、葛兰西开始，将批判重点从经济转向文化和意识形态。",thinkers:[{name:"卢卡奇",sub:"西方马克思主义",era:"1885-1971",influence:10,key:"物化",works:["历史与阶级意识"]},{name:"葛兰西",sub:"西方马克思主义",era:"1891-1937",influence:10,key:"文化霸权",works:["狱中札记"]},{name:"阿尔都塞",sub:"结构马克思主义",era:"1918-1990",influence:9,key:"意识形态国家机器",works:["保卫马克思"]},{name:"布洛赫",sub:"希望哲学",era:"1885-1977",influence:8,key:"希望原理",works:["希望原理"]}],relations:[{from:"卢卡奇",to:"葛兰西",type:"影响"},{from:"葛兰西",to:"阿尔都塞",type:"影响"}],timeline:[],conclusion:"西方马克思主义将批判从工厂扩展到整个文化。",works:[],quotes:[],closingQuote:"哲学家们只是解释了世界。 — 马克思"};
const WESTERN_MARXISM_CIHAI=[{word:"物化",def:"人与人的关系被转化为物的关系，被看作自然的不可改变的。",source:"卢卡奇"},{word:"文化霸权",def:"统治阶级不仅靠暴力，更靠市民社会中的同意来统治。",source:"葛兰西"},{word:"意识形态国家机器",def:"学校教会家庭将人询唤为服从的主体。",source:"阿尔都塞"},{word:"希望的原理",def:"现实本身包含着尚未实现的可能，希望是客观的。",source:"布洛赫"},{word:"阵地战",def:"西方革命必须首先在市民社会的战壕中赢得文化霸权。",source:"葛兰西"}];
const WESTERN_MARXISM_SUB_SCHOOLS=[{name:"黑格尔马克思主义",era:"1920s-1930s",desc:"卢卡奇，物化，阶级意识，具体的总体。"},{name:"葛兰西霸权理论",era:"1920s-1930s",desc:"文化霸权，阵地战，有机知识分子。"},{name:"结构马克思主义",era:"1960s-1970s",desc:"阿尔都塞，认识论断裂，多元决定。"}];
