//政治哲学
const POLITICAL_PHILOSOPHY_DATA={name:"政治哲学",quote:"追问正义、权力与自由的根基。",quoteAuthor:"罗尔斯",subtitle:"从社会契约到分配正义与承认的政治",overview:"政治哲学追问政治秩序的规范性基础。",thinkers:[{name:"罗尔斯",sub:"自由主义",era:"1921-2002",influence:10,key:"作为公平的正义",works:["正义论"]},{name:"诺齐克",sub:"自由至上主义",era:"1938-2002",influence:9,key:"最小国家",works:["无政府、国家与乌托邦"]},{name:"桑德尔",sub:"社群主义",era:"1953-",influence:8,key:"镶嵌的自我",works:["自由主义与正义的局限"]},{name:"阿伦特",sub:"共和主义",era:"1906-1975",influence:9,key:"人的条件",works:["人的条件"]},{name:"伯林",sub:"自由主义",era:"1909-1997",influence:9,key:"消极自由与积极自由",works:["自由论"]}],relations:[{from:"罗尔斯",to:"诺齐克",type:"对立"},{from:"罗尔斯",to:"桑德尔",type:"批判"},{from:"伯林",to:"罗尔斯",type:"影响"}],timeline:[],conclusion:"政治哲学追问我们如何能在一个公正的社会中共同生活。",works:[],quotes:[],closingQuote:"正义是社会制度的第一德性。 — 罗尔斯"};
const POLITICAL_PHILOSOPHY_CIHAI=[{word:"无知之幕",def:"在原初状态中不知道自己的社会位置，从而选择公正原则。",source:"罗尔斯"},{word:"差异原则",def:"社会不平等只有在使最不利者获得最大利益时才被允许。",source:"罗尔斯"},{word:"最小国家",def:"国家仅有保护公民免受暴力和欺诈的功能。",source:"诺齐克"},{word:"消极自由与积极自由",def:"不被干涉的自由与自我主宰的自由。",source:"伯林"},{word:"商议民主",def:"民主不只是投票，是自由平等公民在商议中达成一致。",source:"哈贝马斯"}];
const POLITICAL_PHILOSOPHY_SUB_SCHOOLS=[{name:"自由主义政治哲学",era:"1971-present",desc:"罗尔斯，无知之幕，差异原则，重叠共识。"},{name:"自由至上主义",era:"1974-2002",desc:"诺齐克，最小国家，持有正义。"},{name:"社群主义",era:"1980s-1990s",desc:"桑德尔，自我镶嵌于共同体，正义在善之后。"}];
//伦理学
const ETHICS_DATA={name:"伦理学",quote:"追问人应该如何生活。",quoteAuthor:"苏格拉底",subtitle:"从德性、义务到效用与关怀",overview:"伦理学是哲学最古老的分支，追问人应该如何生活。",thinkers:[{name:"亚里士多德",sub:"德性伦理学",era:"前384-前322",influence:10,key:"中庸之道",works:["尼各马可伦理学"]},{name:"康德",sub:"义务论",era:"1724-1804",influence:10,key:"定言命令",works:["道德形而上学基础"]},{name:"边沁",sub:"功利主义",era:"1748-1832",influence:9,key:"最大幸福原理",works:["道德与立法原理导论"]},{name:"休谟",sub:"道德情感论",era:"1711-1776",influence:9,key:"同情",works:["人性论"]},{name:"吉利根",sub:"关怀伦理学",era:"1936-",influence:8,key:"不同的声音",works:["不同的声音"]}],relations:[{from:"亚里士多德",to:"康德",type:"对立"},{from:"休谟",to:"边沁",type:"影响"}],timeline:[],conclusion:"伦理学的意义不在给出答案而在保持追问。",works:[],quotes:[],closingQuote:"未经审视的人生不值得过。 — 苏格拉底"};
const ETHICS_CIHAI=[{word:"德性",def:"灵魂的卓越，在具体处境中做出恰好的判断。",source:"亚里士多德"},{word:"定言命令",def:"只按你能意愿它成为普遍法则的准则去行动。",source:"康德"},{word:"功利原理",def:"最大多数人的最大幸福是衡量对错的尺度。",source:"边沁"},{word:"自然主义谬误",def:"善是不可定义的简单性质，不能从是推导出应该。",source:"摩尔"},{word:"关怀伦理学",def:"女性以关怀和责任来思考道德，是另一种同样成熟的道德声音。",source:"吉利根"},{word:"中庸之道",def:"德性是两种极端之间的中道，不是算术平均而是恰到好处。",source:"亚里士多德"},{word:"道德情感论",def:"道德的根基不是理性而是同情，理性只是激情的奴隶。",source:"休谟"},{word:"实践智慧",def:"在具体处境中判断什么是恰好的能力，不是理论知识。",source:"亚里士多德"}];
const ETHICS_SUB_SCHOOLS=[{name:"德性伦理学",era:"前4世纪至今",desc:"亚里士多德，德性，实践智慧，中庸，幸福。"},{name:"义务论",era:"18世纪至今",desc:"康德，定言命令，人是目的自身。"},{name:"功利主义",era:"18世纪至今",desc:"边沁和密尔，最大幸福原理，后果论。"},{name:"关怀伦理学",era:"1980s至今",desc:"吉利根，不同的声音，关怀是关系而不是原则。"}];
//基督教哲学
const CHRISTIAN_PHILOSOPHY_DATA={name:"基督教哲学",quote:"信仰寻求理解。",quoteAuthor:"安瑟伦",subtitle:"以理性审视信仰——两千年的理性追问",overview:"基督教哲学是信仰与理性之间两千年的对话。",thinkers:[{name:"奥古斯丁",sub:"教父哲学",era:"354-430",influence:10,key:"信仰寻求理解",works:["忏悔录","上帝之城"]},{name:"托马斯·阿奎那",sub:"经院哲学",era:"1225-1274",influence:10,key:"五路证明",works:["神学大全"]},{name:"安瑟伦",sub:"经院哲学",era:"1033-1109",influence:9,key:"本体论证明",works:["宣讲篇"]},{name:"帕斯卡尔",sub:"基督教存在主义",era:"1623-1662",influence:9,key:"心的理由",works:["思想录"]},{name:"基尔克果",sub:"基督教存在主义",era:"1813-1855",influence:9,key:"信仰的跳跃",works:["恐惧与战栗"]},{name:"蒂利希",sub:"存在主义神学",era:"1886-1965",influence:8,key:"存在的勇气",works:["存在的勇气"]}],relations:[{from:"奥古斯丁",to:"安瑟伦",type:"影响"},{from:"安瑟伦",to:"阿奎那",type:"影响"},{from:"奥古斯丁",to:"帕斯卡尔",type:"影响"},{from:"帕斯卡尔",to:"基尔克果",type:"影响"},{from:"基尔克果",to:"蒂利希",type:"影响"}],timeline:[],conclusion:"信仰寻求理解是理性与启示两千年的对话。",works:[],quotes:[],closingQuote:"信仰寻求理解。 — 安瑟伦"};
const CHRISTIAN_PHILOSOPHY_CIHAI=[{word:"信仰寻求理解",def:"基督教哲学的核心原则，信仰不是无知的避难所而是积极寻求理解的起点。",source:"安瑟伦"},{word:"五路证明",def:"阿奎那为上帝存在提供的五种理性论证。",source:"阿奎那"},{word:"本体论证明",def:"上帝是不能设想比之更大者，必须存在于现实中。",source:"安瑟伦"},{word:"因信称义",def:"人不是因为善行被上帝接纳，而是唯独通过信心。",source:"路德"},{word:"赌注论证",def:"如果你信上帝而上帝存在无限收益，不信而上帝存在无限损失。",source:"帕斯卡尔"},{word:"存在的勇气",def:"面对非存在的三重威胁，人有勇气肯定自己的存在。",source:"蒂利希"},{word:"道成肉身",def:"永恒的圣言在时间中成为完全的人同时保持完全的神。",source:"约翰福音"}];
const CHRISTIAN_PHILOSOPHY_SUB_SCHOOLS=[{name:"教父哲学",era:"2-8世纪",desc:"奥古斯丁，自由意志，原罪，恩典，两城说。"},{name:"经院哲学",era:"11-14世纪",desc:"安瑟伦本体论证明，阿奎那五路证明，恩典成全自然。"},{name:"宗教改革神学",era:"16世纪",desc:"路德，因信称义，唯独信心恩典圣经。"},{name:"现代基督教哲学",era:"19-20世纪",desc:"基尔克果，信仰的跳跃。蒂利希，存在的勇气。"}];
//哲学诠释学
const HERMENEUTICS_DATA={name:"哲学诠释学",quote:"理解不是方法而是存在方式。",quoteAuthor:"伽达默尔",subtitle:"视域融合、效果历史与语言的对话本性",overview:"哲学诠释学是20世纪关于理解本身的本体论哲学。",thinkers:[{name:"海德格尔",sub:"本体论诠释学",era:"1889-1976",influence:10,key:"此在的理解",works:["存在与时间"]},{name:"伽达默尔",sub:"哲学诠释学",era:"1900-2002",influence:10,key:"视域融合",works:["真理与方法"]},{name:"保罗·利科",sub:"诠释学",era:"1913-2005",influence:9,key:"叙事同一性",works:["时间与叙事"]},{name:"狄尔泰",sub:"精神科学",era:"1833-1911",influence:9,key:"解释与理解",works:["精神科学导论"]}],relations:[{from:"狄尔泰",to:"海德格尔",type:"影响"},{from:"海德格尔",to:"伽达默尔",type:"师生"},{from:"伽达默尔",to:"保罗·利科",type:"影响"}],timeline:[],conclusion:"理解永远不是客观的，但也不是主观的。",works:[],quotes:[],closingQuote:"理解不是方法而是存在方式。 — 伽达默尔"};
const HERMENEUTICS_CIHAI=[{word:"视域融合",def:"理解不是重建作者原意，而是两个视域在对话中相遇彼此扩大。",source:"伽达默尔"},{word:"效果历史",def:"真正的历史对象不是过去，而是过去与现在的关系。",source:"伽达默尔"},{word:"前理解",def:"每一次理解之前已带着偏见和传统，不是障碍而是条件。",source:"海德格尔/伽达默尔"},{word:"诠释循环",def:"整体和部分在理解中互相依赖，不是恶性循环而是理解的结构。",source:"海德格尔"},{word:"叙事同一性",def:"我是谁？我是我的故事，自我在叙述中被构成。",source:"保罗·利科"}];
const HERMENEUTICS_SUB_SCHOOLS=[{name:"方法论诠释学",era:"19世纪",desc:"施莱尔马赫，普遍诠释学。狄尔泰，精神科学方法论。"},{name:"本体论诠释学",era:"1927-2002",desc:"海德格尔，理解是此在的存在方式。伽达默尔，视域融合。"},{name:"叙事诠释学",era:"1980s-2005",desc:"保罗·利科，叙事同一性，解释的冲突。"}];
