//后现代主义
const POSTMODERNISM_DATA={name:"后现代主义",quote:"对宏大叙事的怀疑。",quoteAuthor:"利奥塔",subtitle:"真理、主体与历史都是语言的建构",overview:"后现代主义是20世纪下半叶的思想运动，以对元叙事的怀疑为核心。",thinkers:[{name:"利奥塔",sub:"后现代主义",era:"1924-1998",influence:10,key:"对元叙事的怀疑",works:["后现代状况"]},{name:"鲍德里亚",sub:"后现代主义",era:"1929-2007",influence:9,key:"超真实",works:["拟像与拟真"]},{name:"德勒兹",sub:"差异哲学",era:"1925-1995",influence:9,key:"根茎",works:["千高原"]},{name:"罗蒂",sub:"新实用主义",era:"1931-2007",influence:8,key:"偶然反讽团结",works:["偶然、反讽与团结"]}],relations:[{from:"利奥塔",to:"鲍德里亚",type:"影响"},{from:"德勒兹",to:"利奥塔",type:"影响"}],timeline:[],conclusion:"后现代是在宏大叙事崩溃后的清醒。",works:[],quotes:[],closingQuote:"对宏大叙事的怀疑。 — 利奥塔"};
const POSTMODERNISM_CIHAI=[{word:"元叙事",def:"为所有更小的叙事提供统一历史意义的宏大故事。",source:"利奥塔"},{word:"超真实",def:"符号不指向外部，只在与其他符号的相互作用中产生真实。",source:"鲍德里亚"},{word:"拟像",def:"不再有原型的仿真，地图先于领土。",source:"鲍德里亚"},{word:"异识",def:"在两种语言游戏之间没有共同的法官来裁决。",source:"利奥塔"},{word:"弱思想",def:"现代性的强范畴在后现代只能成为弱的再解释。",source:"瓦蒂莫"}];
const POSTMODERNISM_SUB_SCHOOLS=[{name:"利奥塔后现代知识论",era:"1979-1998",desc:"对元叙事的怀疑，知识是碎片化的语言游戏。"},{name:"鲍德里亚符号社会",era:"1970s-2007",desc:"消费社会，拟像，超真实。"}];
//斯多葛学派
const STOICISM_DATA={name:"斯多葛学派",quote:"顺应自然而生活。",quoteAuthor:"芝诺",subtitle:"控制可控的，接受不可控的——古代最持久的伦理智慧",overview:"斯多葛学派是公元前3世纪由芝诺在雅典画廊创立的希腊-罗马哲学学派。",thinkers:[{name:"爱比克泰德",sub:"罗马斯多葛",era:"约55-135",influence:10,key:"可控与不可控",works:["哲学谈话录","手册"]},{name:"塞涅卡",sub:"罗马斯多葛",era:"约前4-65",influence:9,key:"生活的艺术",works:["道德书简"]},{name:"马可·奥勃留",sub:"罗马斯多葛",era:"121-180",influence:10,key:"沉思录",works:["沉思录"]},{name:"西塞罗",sub:"罗马斯多葛",era:"前106-前43",influence:8,key:"自然法",works:["论义务"]}],relations:[{from:"西塞罗",to:"塞涅卡",type:"影响"},{from:"塞涅卡",to:"爱比克泰德",type:"影响"},{from:"爱比克泰德",to:"马可·奥勃留",type:"影响"}],timeline:[],conclusion:"斯多葛从芝诺的画廊到马可奥勃留的军营走了五个世纪。",works:[],quotes:[],closingQuote:"困扰人的不是事物本身而是人对事物的看法。 — 爱比克泰德"};
const STOICISM_CIHAI=[{word:"顺应自然",def:"斯多葛伦理学的最高原则，与宇宙的理性秩序保持一致。",source:"芝诺"},{word:"可控与不可控",def:"幸福来自只想要自己能控制的，而不是想要不可控的外物。",source:"爱比克泰德"},{word:"逻各斯",def:"贯穿一切存在者的宇宙理性和法则。",source:"芝诺/克律西波斯"},{word:"斯多葛练习",def:"早晨预演困难，晚上回顾行为，训练自己的判断力。",source:"爱比克泰德/塞涅卡/马可·奥勃留"},{word:"斯多葛激情理论",def:"激情是认知错误，把无关道德的误判为善或恶。",source:"克律西波斯"}];
const STOICISM_SUB_SCHOOLS=[{name:"早期斯多葛",era:"前3-前2世纪",desc:"芝诺创立，克律西波斯系统化，逻辑物理学伦理学三分。"},{name:"中期斯多葛",era:"前2-前1世纪",desc:"巴内修和波西多纽斯将斯多葛传入罗马。"},{name:"罗马斯多葛",era:"1-2世纪",desc:"塞涅卡，爱比克泰德，马可·奥勃留，斯多葛成为生活的艺术。"}];
//怀疑论
const SKEPTICISM_DATA={name:"怀疑论",quote:"悬搁判断以获得心灵的宁静。",quoteAuthor:"皮浪",subtitle:"对一切教条说我不知道——从古代到现代的怀疑传统",overview:"怀疑论是哲学中最持久的质疑传统，悬搁判断以获得宁静。",thinkers:[{name:"皮浪",sub:"古代怀疑论",era:"约前360-前270",influence:9,key:"悬搁判断",works:["无著作"]},{name:"塞克斯都·恩披里柯",sub:"古代怀疑论",era:"约160-210",influence:10,key:"皮浪学说概要",works:["皮浪学说概要"]},{name:"笛卡尔",sub:"方法论的怀疑",era:"1596-1650",influence:10,key:"我思故我在",works:["第一哲学沉思集"]},{name:"休谟",sub:"经验论怀疑论",era:"1711-1776",influence:10,key:"因果只是习惯",works:["人性论"]},{name:"蒙田",sub:"文艺复兴怀疑论",era:"1533-1592",influence:8,key:"我知道什么",works:["随笔集"]}],relations:[{from:"皮浪",to:"塞克斯都·恩披里柯",type:"继承"},{from:"塞克斯都·恩披里柯",to:"蒙田",type:"影响"},{from:"蒙田",to:"笛卡尔",type:"影响"},{from:"笛卡尔",to:"休谟",type:"继承"}],timeline:[],conclusion:"怀疑论是哲学最诚实的形式。",works:[],quotes:[],closingQuote:"悬搁判断以获得心灵的宁静。 — 皮浪"};
const SKEPTICISM_CIHAI=[{word:"悬搁",def:"对每一个命题既不肯定也不否定，停止判断。",source:"塞克斯都·恩披里柯"},{word:"心灵的宁静",def:"皮浪怀疑论的目标，在悬搁中意外出现的宁静。",source:"塞克斯都·恩披里柯"},{word:"方法论的怀疑",def:"笛卡尔以普遍怀疑为方法找到不可怀疑的第一原理。",source:"笛卡尔"},{word:"我思故我在",def:"我在怀疑这个行动本身不可怀疑，确立了主体性第一原理。",source:"笛卡尔"},{word:"皮浪怀疑论",def:"对每一个命题都能找到同等有力的反命题，因此悬搁是最合理的。",source:"塞克斯都·恩披里柯"}];
const SKEPTICISM_SUB_SCHOOLS=[{name:"皮浪怀疑论",era:"前4世纪-3世纪",desc:"皮浪，悬搁，心灵的宁静，反对一切教条。"},{name:"方法论的怀疑",era:"17世纪",desc:"笛卡尔，普遍怀疑，我思故我在。"},{name:"经验论怀疑论",era:"18世纪",desc:"休谟，因果只是习惯，自我只是一束知觉。"}];
//唯名论
const NOMINALISM_DATA={name:"唯名论",quote:"共相只是名称不是实在。",quoteAuthor:"奥卡姆的威廉",subtitle:"只有个别事物才是真实的存在——中世纪最彻底的哲学革命",overview:"唯名论是中世纪晚期最激进的哲学革命：共相只是心灵创造的名称。",thinkers:[{name:"洛色林",sub:"极端唯名论",era:"约1050-1125",influence:7,key:"共相只是词语的声响",works:["失传"]},{name:"阿伯拉尔",sub:"概念论",era:"1079-1142",influence:8,key:"共相是概念",works:["是与否"]},{name:"奥卡姆的威廉",sub:"唯名论",era:"约1287-1347",influence:10,key:"奥卡姆剃刀",works:["逻辑大全"]},{name:"邓斯·司各脱",sub:"此性论",era:"约1266-1308",influence:9,key:"此性",works:["牛津评注"]}],relations:[{from:"洛色林",to:"阿伯拉尔",type:"师生"},{from:"阿伯拉尔",to:"邓斯·司各脱",type:"影响"},{from:"邓斯·司各脱",to:"奥卡姆的威廉",type:"批判"}],timeline:[],conclusion:"奥卡姆剃刀剃除了形而上学的冗余。",works:[],quotes:[],closingQuote:"如无必要，勿增实体。 — 奥卡姆的威廉"};
const NOMINALISM_CIHAI=[{word:"共相问题",def:"普遍的类是独立存在的实体还是心灵创造的名称。",source:"中世纪哲学"},{word:"奥卡姆剃刀",def:"如无必要勿增实体，剃除一切不必要的抽象实体。",source:"奥卡姆的威廉"},{word:"此性",def:"使个别事物成为这一个个而不是那一个个的不可还原的原则。",source:"邓斯·司各脱"},{word:"概念论",def:"共相既非实体也非词语，是心灵在观察相似性后形成的概念。",source:"阿伯拉尔"},{word:"唯名论与个体主义",def:"只有个别事物真实存在，个体的权利是第一性的。",source:"奥卡姆"}];
const NOMINALISM_SUB_SCHOOLS=[{name:"极端唯名论",era:"11-12世纪",desc:"洛色林，共相只是词语的声响。"},{name:"概念论",era:"12世纪",desc:"阿伯拉尔，中间立场，共相是心灵中的概念。"},{name:"奥卡姆唯名论",era:"14世纪",desc:"奥卡姆的威廉，剃刀原则，共相只是心灵的符号。"}];
//批判理论
const CRITICAL_THEORY_DATA={name:"批判理论",quote:"传统理论描述世界——批判理论旨在解放。",quoteAuthor:"霍克海默",subtitle:"揭示权力、知识与意识形态的纠缠",overview:"批判理论是法兰克福学派的核心方法，将哲学、社会学和精神分析融合为对社会的彻底批判。",thinkers:[{name:"霍克海默",sub:"第一代",era:"1895-1973",influence:10,key:"传统理论与批判理论",works:["传统理论与批判理论"]},{name:"阿多诺",sub:"第一代",era:"1903-1969",influence:10,key:"否定辩证法",works:["否定辩证法"]},{name:"哈贝马斯",sub:"第二代",era:"1929-",influence:10,key:"交往理性",works:["交往行为理论"]},{name:"霍耐特",sub:"第三代",era:"1949-",influence:8,key:"为承认而斗争",works:["为承认而斗争"]},{name:"萨义德",sub:"后殖民批判",era:"1935-2003",influence:9,key:"东方学",works:["东方学"]}],relations:[{from:"霍克海默",to:"阿多诺",type:"友谊"},{from:"阿多诺",to:"哈贝马斯",type:"批判"},{from:"哈贝马斯",to:"霍耐特",type:"继承"}],timeline:[],conclusion:"批判理论是一个不断扩展的解放承诺。",works:[],quotes:[],closingQuote:"传统理论描述世界——批判理论旨在解放。 — 霍克海默"};
const CRITICAL_THEORY_CIHAI=[{word:"批判理论",def:"与传统理论对立，追问世界为什么是这样和如何才能不同。",source:"霍克海默"},{word:"交往理性",def:"不是主体对客体的理性，而是主体间在自由对话中达成的理性。",source:"哈贝马斯"},{word:"承认",def:"社会斗争的根本动力不是利益，而是被剥夺承认的道德伤害。",source:"霍耐特"},{word:"东方学",def:"东方不是自然的地理事实，是西方在学术中建构的他者。",source:"萨义德"},{word:"属下",def:"被殖民被边缘化的底层，从来不能用自己的声音说话。",source:"斯皮瓦克"}];
const CRITICAL_THEORY_SUB_SCHOOLS=[{name:"第一代法兰克福学派",era:"1930s-1970",desc:"霍克海默阿多诺，工具理性批判，文化工业。"},{name:"第二代交往转向",era:"1980s-2000s",desc:"哈贝马斯，交往理性，公共领域，商议民主。"},{name:"第三代承认理论",era:"1990s-present",desc:"霍耐特，承认，为承认而斗争。"},{name:"后殖民批判",era:"1978-present",desc:"萨义德，斯皮瓦克，霍米巴巴，揭示知识与权力的纠缠。"}];
//社群主义
const COMMUNITARIANISM_DATA={name:"社群主义",quote:"自我镶嵌于共同体之中。",quoteAuthor:"桑德尔",subtitle:"正义、善与归属不可分离",overview:"社群主义是20世纪80年代从对罗尔斯自由主义的批判中兴起的思想运动。",thinkers:[{name:"桑德尔",sub:"社群主义",era:"1953-",influence:9,key:"镶嵌的自我",works:["自由主义与正义的局限"]},{name:"麦金太尔",sub:"社群主义",era:"1929-",influence:9,key:"德性传统",works:["德性之后"]},{name:"泰勒",sub:"社群主义",era:"1931-",influence:9,key:"本真性伦理",works:["自我的根源"]},{name:"沃尔泽",sub:"社群主义",era:"1935-",influence:8,key:"正义诸领域",works:["正义诸领域"]}],relations:[{from:"泰勒",to:"桑德尔",type:"影响"},{from:"麦金太尔",to:"桑德尔",type:"影响"}],timeline:[],conclusion:"自我不是在真空中选择，而是在共同体中被构成。",works:[],quotes:[],closingQuote:"自我镶嵌于共同体之中。 — 桑德尔"};
const COMMUNITARIANISM_CIHAI=[{word:"镶嵌的自我",def:"我不是无牵无挂的选择者，而是已有特定共同体身份的存在者。",source:"桑德尔"},{word:"德性与传统",def:"德性不能在抽象规则中被学习，只能在具体的实践和传统中被传承。",source:"麦金太尔"},{word:"复合平等",def:"不同领域有不同正义，阻止一领域的成功转化为另一领域的支配。",source:"沃尔泽"},{word:"本真性",def:"成为自己不是在孤独中而是在与他人的对话中。",source:"泰勒"},{word:"自由主义-社群主义之争",def:"个体权利优先于善，还是善在正义之先。",source:"桑德尔/麦金太尔"}];
const COMMUNITARIANISM_SUB_SCHOOLS=[{name:"桑德尔公民共和主义",era:"1980s-present",desc:"镶嵌的自我，正义在善之后。"},{name:"麦金太尔德性传统",era:"1980s-present",desc:"启蒙道德工程的失败，回到亚里士多德。"},{name:"沃尔泽复合平等",era:"1980s-present",desc:"正义诸领域，不同领域有不同正义。"}];
//技术哲学
const PHILOSOPHY_OF_TECHNOLOGY_DATA={name:"技术哲学",quote:"技术不是中立的工具——它重塑了人的存在方式。",quoteAuthor:"海德格尔",subtitle:"追问技术的本质——从工具论到座架",overview:"技术哲学追问技术不是中立的工具而是揭示世界的方式。",thinkers:[{name:"海德格尔",sub:"技术哲学",era:"1889-1976",influence:10,key:"座架",works:["技术的追问"]},{name:"埃吕尔",sub:"技术自主论",era:"1912-1994",influence:9,key:"技术系统",works:["技术社会"]},{name:"芬伯格",sub:"技术批判理论",era:"1943-",influence:8,key:"民主化技术",works:["技术批判理论"]},{name:"芒福德",sub:"技术史",era:"1895-1990",influence:8,key:"巨机器",works:["技术与文明"]},{name:"麦克卢汉",sub:"媒介理论",era:"1911-1980",influence:8,key:"媒介即讯息",works:["理解媒介"]}],relations:[{from:"海德格尔",to:"埃吕尔",type:"影响"},{from:"埃吕尔",to:"芬伯格",type:"批判"},{from:"芒福德",to:"埃吕尔",type:"影响"}],timeline:[],conclusion:"技术不是我们在使用的中立工具，它重新塑造了我们自己。",works:[],quotes:[],closingQuote:"技术不是中立的工具。 — 海德格尔"};
const PHILOSOPHY_OF_TECHNOLOGY_CIHAI=[{word:"座架",def:"现代技术的本质，将一切存在者以可计算可利用的方式去揭示。",source:"海德格尔"},{word:"技术自主论",def:"技术不再是中立的工具，效率成为一切领域的唯一标准。",source:"埃吕尔"},{word:"媒介即讯息",def:"不是内容而是媒介本身的形式从根本上重塑社会。",source:"麦克卢汉"},{word:"民主化技术",def:"技术不是宿命，可以被社会选择重塑，让被技术影响的人参予设计。",source:"芬伯格"},{word:"巨机器",def:"古代金字塔和现代官僚系统分享同一种逻辑：将人变成可替换的零件。",source:"芒福德"}];
const PHILOSOPHY_OF_TECHNOLOGY_SUB_SCHOOLS=[{name:"海德格尔技术现象学",era:"1950s",desc:"座架，现代技术是揭示世界的方式。"},{name:"技术自主论",era:"1950s-1990s",desc:"埃吕尔，技术系统，芒福德，巨机器。"},{name:"技术批判理论",era:"1990s-present",desc:"芬伯格，民主化技术。"}];
