import assert from 'node:assert/strict';
import {toolResultView, safeResultUrl} from '../src/data/toolResultView.js';

const empty = {query:'后出师表 诸葛亮',results:[],catalogue_matches:[],search_coverage:{indexed_books:410,indexed_chapter_entries:12435},semantic_gate:{min_cosine:0.5}};
const view = toolResultView('search_books', JSON.stringify(empty));
assert.match(view.headline,/未检索到/);
assert.match(view.meta.join(' '),/索引覆盖 410/);
assert.match(view.meta.join(' '),/12,435/);
assert.match(view.note,/不代表/);
assert.deepEqual(JSON.parse(view.rawText),empty);
assert.ok(!view.headline.includes('semantic_gate'));

const metadata = toolResultView('search_books',{results:[{book_title:'论语',match_type:'book_metadata',evidence_scope:'catalogue'}]});
assert.match(metadata.headline,/书目线索/);
assert.match(metadata.note,/尚未取得/);
const partial = toolResultView('search_scholarship',{results:[{title:'A paper'}],READABLE_RESULT_COUNT:0,provider_errors:[{provider:'openalex',error:'RATE_LIMITED'}]});
assert.equal(partial.items.length,1);
assert.match(partial.warnings[0],/限流/);
assert.match(partial.meta[0],/0 条/);
assert.match(partial.note,/不等于已读/);
const failure = toolResultView('search_scholarship',{error:"'NoneType' object is not subscriptable"});
assert.match(failure.headline,/工具执行未成功/);
assert.ok(failure.rawText.includes('NoneType'));
const mixed = toolResultView('websearch',{error:'upstream failed',results:[{title:'Returned source'}]});
assert.equal(mixed.items.length,1);
assert.match(mixed.note,/部分记录/);
assert.match(toolResultView('unknown',{status:'blocked',message:'暂时不可用'}).headline,/未执行/);

const noQuote = toolResultView('verify_quote',{found:false,matches:[],coverage:{searched_chapters:22,directory_consistent:false}});
assert.match(noQuote.headline,/未找到/);
assert.match(noQuote.note,/只限本次版本/);
assert.match(noQuote.warnings[0],/不完整/);
const read = toolResultView('get_chapter',{title:'原文',text:'内容'.repeat(500),has_more:true});
assert.match(read.headline,/片段/);
assert.match(read.note,/并非全文/);
assert.equal(JSON.parse(read.rawText).text.length,1000);
const broken = toolResultView('search_books','{"results":[...');
assert.match(broken.headline,/未能完整解析/);
assert.equal(broken.rawText,'{"results":[...');
assert.equal(toolResultView('unknown',false).headline,'false');
assert.equal(toolResultView('unknown',0).headline,'0');
assert.equal(toolResultView('unknown',null).headline,'');
assert.equal(safeResultUrl('javascript:alert(1)'),null);
assert.equal(safeResultUrl('https://user:secret@example.com'),null);
assert.equal(safeResultUrl('https://example.com/paper'),'https://example.com/paper');
assert.match(toolResultView('search_books',empty,false).headline,/No sufficiently/);
console.log('Tool result presentation: evidence scope, failures, raw preservation and link safety passed');

const memoryRaw={memories:[],memory_profile:'## 长期关注\n语言哲学。\n\n## 阅读\n《哲学研究》',user_settings:{about:'我是高中生',custom_instructions:'分步骤讲解'}};
const memory=toolResultView('recall_account_memory',memoryRaw);
assert.equal(memory.documents.length,2);
assert.match(memory.documents[0].text,/高中生/);
assert.match(memory.documents[1].text,/## 阅读/);
assert.match(memory.headline,/已读取/);
assert.deepEqual(JSON.parse(memory.rawText),memoryRaw);
assert.match(toolResultView('recall_account_memory',{memories:[],memory_profile:''}).headline,/还没有/);
assert.match(toolResultView('recall_account_memory',{error:'MEMORY_DISABLED'}).headline,/已关闭/);
assert.match(toolResultView('remember_account_memory',{memory:{memory_id:'m1',text:'原话'}}).headline,/已保存/);
assert.match(toolResultView('forget_account_memory',{deleted:false}).headline,/未找到/);
assert.equal(toolResultView('search_account_history',{results:[{conversation_id:'c/1',title:'语言',excerpt:'以前的问题'}]}).items[0].url,'/agent/c/c%2F1');
assert.match(toolResultView('philosopher_concepts',{concepts:[{term:'永恒轮回',canon:'解释'}]}).items[0].excerpt,/解释/);
assert.match(toolResultView('philosopher_memory',{memories:[{event:'写作',year:1882,significance:'相关背景'}]}).items[0].meta,/1882/);
assert.match(toolResultView('philosopher_user',{likely_misconceptions:[{claim:'错误命题',fact:'澄清'}]}).note,/不是对当前用户/);
assert.match(toolResultView('analyze_argument',{conclusion:'结论',analysis:'实际分析'}).documents[1].text,/实际分析/);
for(const key of ['success','accepted','ok'])assert.match(toolResultView('unknown',{[key]:false}).headline,/未成功/);
console.log('Memory, history, persona, generic analysis and failed operation presentations passed');
