name = "deepphilosophy-auth"
main = "src/index.js"
compatibility_date = "2025-07-21"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "deepphilosophy_db"
database_name = "deepphilosophy-db"
database_id = "7db39390-6088-4cf5-a283-4697fc876091"

[vars]
JWT_SECRET = "dph-v1-auth-secret-key-2025"

[[routes]]
pattern = "deepphilosophy.top/api/auth/*"
zone_name = "deepphilosophy.top"
